name = "rklib"
author = "Jacob Williams"
copyright  = "Copyright (c) 2022-2023, Jacob Williams"
license = "BSD-3"
description = "Fixed and variable-step Runge-Kutta solvers in Modern Fortran"
homepage = "https://github.com/jacobwilliams/rklib"
keywords = ["ode"]

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[dependencies]
roots-fortran = { git = "https://github.com/jacobwilliams/roots-fortran", rev = "1.4.0" }

[dev-dependencies]
pyplot-fortran = { git = "https://github.com/jacobwilliams/pyplot-fortran", tag = "3.4.0" }
FACE = { git="https://github.com/szaghi/FACE.git" }
mpfun2020-var1 = { git="https://github.com/jacobwilliams/mpfun2020-var1.git", tag = "20.1"}

[library]
source-dir = "src"

[install]
library = true